### ISSUE TITLE
Error reporting on using powerukkit 

### ISSUE THREAD

**Issue by wlm1455925277** [Vrekt/ArcNukkit#1]
[36m17:55:41[m [[34mINFO [m] 璇诲彇 Arc v1.2 涓�[36m17:55:41[m [[1;31mERROR[m] Catchingjava.lang.UnsupportedClassVersionError: me/vrekt/arc/Arc has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_291]        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_291]        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_291]        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_291]        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_291]        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_291]        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_291]        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_291]        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_291]        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[1.jar:?]        at cn.nukkit.plugin.JavaPluginLoader.getClassByName(JavaPluginLoader.java:153) ~[1.jar:?]        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:39) ~[1.jar:?]        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[1.jar:?]        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_291]        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:50) ~[1.jar:?]        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:123) ~[1.jar:?]        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:294) ~[1.jar:?]        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:160) ~[1.jar:?]        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:152) ~[1.jar:?]        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:148) ~[1.jar:?]        at cn.nukkit.Server.<init>(Server.java:686) ~[1.jar:?]        at cn.nukkit.Nukkit.main(Nukkit.java:199) [1.jar:?][36m17:55:41[m [[34mINFO [m] Stopping other threads

**Comment by Vrekt** [comment]
~ArcNukkit was made with Java 11. So in turn you need java 11 installed to run it on your server.~

~Right now you're using Java 8. PowerNukkit should be fine with Java 11 but I'm not sure, let me know.~

**Comment by Vrekt** [comment]
I've updated the releases page. The new 1.3 release supports Java 8 now.

Let me know if there is anything else.

**Comment by wlm1455925277** [comment]
Thanks, author NP

**Comment by wlm1455925277** [comment]
I&nbsp;use&nbsp;toolbox&nbsp;to&nbsp;test,&nbsp;except&nbsp;for&nbsp;flight,&nbsp;other&nbsp;functions&nbsp;can&nbsp;be&nbsp;used,&nbsp;and&nbsp;there&nbsp;is&nbsp;a&nbsp;modified&nbsp;version.&nbsp;I&nbsp;hope&nbsp;to&nbsp;prevent&nbsp;the&nbsp;function&nbsp;of&nbsp;this&nbsp;software,&nbsp;and&nbsp;hang&nbsp;the&nbsp;link&nbsp;of&nbsp;China&nbsp;VPN&nbsp;[may&nbsp;need]:&nbsp;https://wwe.lanzoui.com/iHkAcqu9a7c&nbsp;&nbsp;You&nbsp;can&nbsp;refer&nbsp;to&nbsp;him&nbsp;to&nbsp;do,&nbsp;then&nbsp;some&nbsp;functions,&nbsp;hope&nbsp;to&nbsp;update,&nbsp;thank&nbsp;you
------&nbsp;原始邮件&nbsp;------
***@***.***&gt;;
发送时间:2021年7月16日(星期五)&nbsp;上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:Re:&nbsp;[Vrekt/ArcNukkit]&nbsp;Error&nbsp;reporting&nbsp;on&nbsp;using&nbsp;powerukkit&nbsp;&nbsp;(#1)



 
I've updated the releases page. The new 1.3 release supports Java 8 now.
 
Let me know if there is anything else.
 
&mdash;

**Comment by wlm1455925277** [comment]
It&nbsp;is&nbsp;suggested&nbsp;to&nbsp;add&nbsp;the&nbsp;white&nbsp;list&nbsp;of&nbsp;players&nbsp;that&nbsp;do&nbsp;not&nbsp;check,&nbsp;and&nbsp;the&nbsp;command&nbsp;is&nbsp;expected&nbsp;to&nbsp;be&nbsp;updated
------&nbsp;原始邮件&nbsp;------
***@***.***&gt;;
发送时间:2021年7月16日(星期五)&nbsp;上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:Re:&nbsp;[Vrekt/ArcNukkit]&nbsp;Error&nbsp;reporting&nbsp;on&nbsp;using&nbsp;powerukkit&nbsp;&nbsp;(#1)



 
I've updated the releases page. The new 1.3 release supports Java 8 now.
 
Let me know if there is anything else.
 
&mdash;
